spring:
  application:
    name: item-service
  rabbitmq:
    host: www.zhixiongshouci.top
    port: 5672
    username: admin
    password: 753211lm
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh